version: "3.8"
services:
  orderapp:
    image: orderapp
    build: .
    restart: always
    container_name: testspring
    ports:
      - 9999:9999
  testvue:
    image: testvue
    container_name: vue
    ports:
    - 8088:80
    depends_on:
      - orderapp
    links:
      - orderapp
